GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/64a5a473d7238be7f1d23619

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "minätaas",
    "number": "1234"
}

###

DELETE http://localhost:3001/api/persons/770766276544